### ISSUE TITLE
RTX 4090 CUDA out of memory issue + Question about framework detail

### ISSUE THREAD

**Issue by jimmychuang95** [cyjdlhy/DreamInit#1]
Nice work! I noticed in your paper that you used an RTX 3090 24GB for training. However, when I use an RTX 4090 24GB and try different prompts, I keep encountering a "CUDA out of memory" error, indicating that 24GB VRAM is clearly insufficient. Could you suggest any settings to resolve this issue?

**Comment by jimmychuang95** [comment]
I tried using --vram_O and reducing --c_batch_size to 1, which did decrease memory usage, but will this affect the output results?

**Comment by lutao2021** [comment]
Our experiments of phase I are mainly conducted on an A40 48GB GPU.

But we think removing the T5 text encoder in the IF model after text embedding is helpful.

You can attempt to remove it in the GPU memory.

**Comment by jimmychuang95** [comment]
@lutao2021 Thanks for the reply! One more quick question about the paper. In your paper, you mentioned that color and opacity were supervised using a 2D diffusion model (Deepfloyd IF + SDS in implementation details), but there doesn’t seem to be a detailed description of this. Could you clarify if it is similar to the second stage, where the rendered 3DGS image is input into IF with added noise and only the SDS loss is used as a gradient to backpropagate through the entire network (including the encoder, decoder, GIP, and GTF blocks)? I'd really appreciate if you could share some details on this process! Thank you very much.

**Comment by lutao2021** [comment]
> @lutao2021 Thanks for the reply! One more quick question about the paper. In your paper, you mentioned that color and opacity were supervised using a 2D diffusion model (Deepfloyd IF + SDS in implementation details), but there doesn’t seem to be a detailed description of this. Could you clarify if it is similar to the second stage, where the rendered 3DGS image is input into IF with added noise and only the SDS loss is used as a gradient to backpropagate through the entire network (including the encoder, decoder, GIP, and GTF blocks)? I'd really appreciate if you could share some details on this process! Thank you very much.

The target of the first stage is to construct the rough but semantic-alignment 3D GS model. Therefore, we choose to place the Gaussian ellipsoid uniformly in the space. Considering that the other properties are irrelevant to this, we only train the opacity and color properties using SDS loss. Therefore, we tend to choose a better diffusion model in the semantic aspect but with low resolution (64) to calculate the SDS loss.

In the second stage, we did not change any details of the original method. We loaded the filtered 3D GS model directly before training started.

**Comment by jimmychuang95** [comment]
@lutao2021  Understood, how about the encoder, decoder and two proposed blocks? Are they pre-trained?

**Comment by lutao2021** [comment]
> @lutao2021 Understood, how about the encoder, decoder and two proposed blocks? Are they pre-trained?

No, the target of these blocks is only for constructing the information interaction.

**Comment by jimmychuang95** [comment]
> > @lutao2021 Understood, how about the encoder, decoder and two proposed blocks? Are they pre-trained?
> 
> No, the target of these blocks is only for constructing the information interaction.

So the weight inside encoder/decoder and Wq, Wk, Wv are all fixed during training right?

**Comment by lutao2021** [comment]
> > > @lutao2021 Understood, how about the encoder, decoder and two proposed blocks? Are they pre-trained?
> > 
> > 
> > No, the target of these blocks is only for constructing the information interaction.
> 
> So the weight inside encoder/decoder and Wq, Wk, Wv are all fixed during training right?

No, they are trainable

**Comment by jimmychuang95** [comment]
@lutao2021  Understood, so they are also update by gradient provided by FloydIF sds loss as well, aren't they?

**Comment by lutao2021** [comment]
> @lutao2021 Understood, so they are also update by gradient provided by FloydIF sds loss as well, aren't they?

Yes, you are right.

**Comment by jimmychuang95** [comment]
@lutao2021 Thanks for replying <3
