### ISSUE TITLE
Code release for FlowDreamer

### ISSUE THREAD

**Issue by jimmychuang95** [cyjdlhy/DreamInit#2]
May I ask when you expect to release the code for FlowDremaer? Looking forward to it!

**Comment by cyjdlhy** [comment]
Thank you For your support, we are in the review period, waiting for a good result after we will open the source code.

发件人: jimmychuang95 ***@***.***>
日期: 星期一, 2024年11月25日 15:00
收件人: cyjdlhy/DreamInit ***@***.***>
抄送: Subscribed ***@***.***>
主题: [cyjdlhy/DreamInit] Code release for FlowDreamer (Issue #2)

May I ask when you expect to release the code for FlowDremaer? Looking forward to it!

―

**Comment by jimmychuang95** [comment]
> Thank you For your support, we are in the review period, waiting for a good result after we will open the source code.

Got it. Good luck with the review!
